### ISSUE TITLE
middlewares shouldn't use '_doc' on object

### ISSUE THREAD

**Issue by bikov** [Enigmatis/polaris#42]
problem:
if using lean(https://mongoosejs.com/docs/api.html#query_Query-lean) on the db query there will be no _doc
you can use toObject(https://mongoosejs.com/docs/api.html#document_Document-toObject) function instead
also to check if this object is mongoose document you can use: 'object instanceof Mongoose.Model'

**Comment by osher-sade** [comment]
#51
